/*
Meshes auto-generated by: https://github.com/pmndrs/gltfjsx
Author: littlehustler (https://sketchfab.com/littlehustler)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-backpack-with-cat-ears-5d8a50093fd44bbd951d8cdd27d2b171
Title: Cute backpack with cat ears
*/

import { useGLTF } from "@react-three/drei";
import backpackScene from "../assets/backpack.glb";

const Backpack = (props) => {
  const { nodes, materials } = useGLTF(backpackScene);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        position={[0.175, 0, 0.015]}
      />
    </group>
  );
};

export default Backpack;
