/*
Meshes auto-generated by: https://github.com/pmndrs/gltfjsx
Author: laurenk1840 (https://sketchfab.com/laurenk1840)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bonsai-f41f95e3913b44e5ae934ad765634249
Title: Bonsai
*/

import { useGLTF } from "@react-three/drei";
import bonsaiScene from "../assets/bonsai.glb";
import { useRef } from "react";

const Bonsai = (props) => {
  const ref = useRef();
  const { scene } = useGLTF(bonsaiScene);
  return (
    <mesh ref={ref}>
      <primitive object={scene} {...props} />
    </mesh>
  );
};

useGLTF.preload(bonsaiScene);
export default Bonsai;
