/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: laurenk1840 (https://sketchfab.com/laurenk1840)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bonsai-f41f95e3913b44e5ae934ad765634249
Title: Bonsai
*/

import { useGLTF } from "@react-three/drei";
import bonsaiScene from "../assets/bonsai.glb";

const Bonsai = (props) => {
  const { nodes, materials } = useGLTF(bonsaiScene);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube1_bark_0.geometry}
        material={materials.bark}
        position={[1.136, -0.007, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube7_pot_0.geometry}
        material={materials.material}
        position={[2.371, 0, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube8_soil_0.geometry}
        material={materials.soil}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane4_leaf_0.geometry}
        material={materials.leaf}
        position={[3.593, 5.553, -1.971]}
        rotation={[0.371, 0, 0]}
        scale={[0.702, 0.421, 0.421]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane5_leaf_0.geometry}
        material={materials.leaf}
        position={[1.017, 7.413, 1.208]}
        rotation={[3.124, 0.387, 2.794]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane6_leaf_0.geometry}
        material={materials.leaf}
        position={[3.328, 7.833, -0.519]}
        rotation={[0.569, 0.01, -0.015]}
        scale={[1.388, 0.833, 0.833]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane7_leaf_0.geometry}
        material={materials.leaf}
        position={[1.737, 6.169, 0.016]}
        rotation={[-0.449, 0, 0]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane8_leaf_0.geometry}
        material={materials.leaf}
        position={[5.926, 7.359, -1.835]}
        rotation={[0.602, 0, 0]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane9_leaf_0.geometry}
        material={materials.leaf}
        position={[2.386, 7.908, -0.654]}
        rotation={[-2.75, 0.263, -3]}
        scale={[1.226, 0.736, 0.736]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane10_leaf_0.geometry}
        material={materials.leaf}
        position={[-0.857, 7.815, -0.018]}
        rotation={[-2.947, -0.049, -2.899]}
        scale={[0.664, 0.399, 0.399]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane11_leaf_0.geometry}
        material={materials.leaf}
        position={[2.386, 7.908, -0.654]}
        rotation={[-2.75, 0.263, -3]}
        scale={[1.226, 0.736, 0.736]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane12_leaf_0.geometry}
        material={materials.leaf}
        position={[2.386, 7.908, -0.654]}
        rotation={[-2.75, 0.263, -3]}
        scale={[1.226, 0.736, 0.736]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane13_leaf_0.geometry}
        material={materials.leaf}
        position={[0.191, 6.038, 0.232]}
        rotation={[-2.648, -0.44, -2.991]}
        scale={[1.226, 0.736, 0.736]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane14_leaf_0.geometry}
        material={materials.leaf}
        position={[2.295, 7.407, 1.611]}
        rotation={[0.593, 0, -0.125]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane15_leaf_0.geometry}
        material={materials.leaf}
        position={[-1.756, 5.641, 3.362]}
        rotation={[-2.505, -0.334, -3.009]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane16_leaf_0.geometry}
        material={materials.leaf}
        position={[-0.508, 5.651, 3.163]}
        rotation={[0.593, 0, 0]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane17_leaf_0.geometry}
        material={materials.leaf}
        position={[3.362, 4.77, 0.289]}
        rotation={[0, -0.527, 0.118]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane18_leaf_0.geometry}
        material={materials.leaf}
        position={[0.333, 3.68, 0.016]}
        rotation={[0.593, 0, 0]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane19_leaf_0.geometry}
        material={materials.leaf}
        position={[-0.857, 7.815, -0.018]}
        rotation={[-2.947, -0.049, -2.899]}
        scale={[0.664, 0.399, 0.399]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane20_leaf_0.geometry}
        material={materials.leaf}
        position={[-0.438, 7.804, 0.085]}
        rotation={[-0.389, -0.477, -0.291]}
        scale={[0.664, 0.399, 0.399]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane21_leaf_0.geometry}
        material={materials.leaf}
        position={[3.609, 8.751, 0.447]}
        rotation={[0.371, 0, 0]}
        scale={[0.702, 0.421, 0.421]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane22_leaf_0.geometry}
        material={materials.leaf}
        position={[3.056, 8.69, 0.188]}
        rotation={[2.799, 0.084, -3.069]}
        scale={[0.702, 0.421, 0.421]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane23_leaf_0.geometry}
        material={materials.leaf}
        position={[2.388, 4.511, -0.608]}
        rotation={[-2.885, 0.964, 2.658]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane24_leaf_0.geometry}
        material={materials.leaf}
        position={[-0.152, 8.423, -0.358]}
        rotation={[0.371, 0, 0]}
        scale={[0.702, 0.421, 0.421]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane25_leaf_0.geometry}
        material={materials.leaf}
        position={[-0.848, 8.697, -0.388]}
        rotation={[-2.75, 0.263, -3]}
        scale={[1.226, 0.736, 0.736]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane26_leaf_0.geometry}
        material={materials.leaf}
        position={[0.057, 6.518, -0.385]}
        rotation={[0.593, 0, -0.125]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane27_leaf_0.geometry}
        material={materials.leaf}
        position={[-1.932, 7.021, -0.256]}
        rotation={[-2.871, 0.273, 2.7]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane28_leaf_0.geometry}
        material={materials.leaf}
        position={[2.923, 5.641, -1.345]}
        rotation={[-2.505, -0.334, -3.009]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane29_leaf_0.geometry}
        material={materials.leaf}
        position={[1.429, 4.808, 0.625]}
        rotation={[-2.505, -0.334, -3.009]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane30_leaf_0.geometry}
        material={materials.leaf}
        position={[5.339, 6.988, -2.835]}
        rotation={[-0.449, 0.944, 0]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane31_leaf_0.geometry}
        material={materials.leaf}
        position={[0.815, 5.001, -0.332]}
        rotation={[1.874, -0.02, 2.783]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane32_leaf_0.geometry}
        material={materials.leaf}
        position={[2.435, 5.179, -0.307]}
        rotation={[-0.509, 0.111, -0.046]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane33_leaf_0.geometry}
        material={materials.leaf}
        position={[3.852, 7.009, -2.111]}
        rotation={[-0.957, 0.016, 0.009]}
        scale={[1.388, 0.833, 0.833]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane34_leaf_0.geometry}
        material={materials.leaf}
        position={[-1.242, 7.54, -0.013]}
        rotation={[2.585, -0.255, Math.PI]}
        scale={[0.702, 0.421, 0.421]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane35_leaf_0.geometry}
        material={materials.leaf}
        position={[-1.736, 4.404, 0.231]}
        rotation={[-2.549, -0.065, Math.PI]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane36_leaf_0.geometry}
        material={materials.leaf}
        position={[4.582, 5.204, -0.892]}
        rotation={[0.593, 0, -0.125]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane37_leaf_0.geometry}
        material={materials.leaf}
        position={[2.927, 6.635, -2.463]}
        rotation={[2.263, -0.061, -2.85]}
        scale={[1.226, 0.736, 0.736]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane38_leaf_0.geometry}
        material={materials.leaf}
        position={[-0.355, 4.58, 1.321]}
        rotation={[-0.421, 0, 0]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane39_leaf_0.geometry}
        material={materials.leaf}
        position={[-0.981, 6.537, -0.737]}
        rotation={[3.054, 0.823, -2.781]}
        scale={[0.664, 0.399, 0.399]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane40_leaf_0.geometry}
        material={materials.leaf}
        position={[4.77, 6.419, -2]}
        rotation={[0.371, 0, 0]}
        scale={[0.702, 0.421, 0.421]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane41_leaf_0.geometry}
        material={materials.leaf}
        position={[4.164, 6.358, -2.192]}
        rotation={[2.799, 0.084, -3.069]}
        scale={[0.702, 0.421, 0.421]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane42_leaf_0.geometry}
        material={materials.leaf}
        position={[2.91, 7.363, -1.772]}
        rotation={[2.166, -0.09, -2.857]}
        scale={[1.226, 0.736, 0.736]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane43_leaf_0.geometry}
        material={materials.leaf}
        position={[4.034, 7.168, -1.451]}
        rotation={[0.593, 0, -0.125]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane44_leaf_0.geometry}
        material={materials.leaf}
        position={[1.804, 5.867, 1.014]}
        rotation={[0.522, -0.513, -0.144]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane45_leaf_0.geometry}
        material={materials.leaf}
        position={[2.649, 3.563, 0.234]}
        rotation={[0.593, 0, 0]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane46_leaf_0.geometry}
        material={materials.leaf}
        position={[2.328, 2.914, -0.425]}
        rotation={[-0.755, 0, 0]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane47_leaf_0.geometry}
        material={materials.leaf}
        position={[-1.485, 4.94, 2.044]}
        rotation={[3.124, 0.387, 2.794]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane48_leaf_0.geometry}
        material={materials.leaf}
        position={[4.463, 4.95, -1.879]}
        rotation={[-1.818, 0.003, 0.018]}
        scale={[1.388, 0.833, 0.833]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane49_leaf_0.geometry}
        material={materials.leaf}
        position={[-1.218, 3.608, -0.396]}
        rotation={[2.263, -0.061, -2.85]}
        scale={[1.226, 0.736, 0.736]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane50_leaf_0.geometry}
        material={materials.leaf}
        position={[1.442, 7.001, 1.655]}
        rotation={[-2.771, -1.522, -Math.PI]}
        scale={[0.702, 0.421, 0.421]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane51_leaf_0.geometry}
        material={materials.leaf}
        position={[1.775, 6.704, 0.988]}
        rotation={[0.117, 0.189, -0.098]}
        scale={[1.226, 0.736, 0.736]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane52_leaf_0.geometry}
        material={materials.leaf}
        position={[0.078, 6.112, -1.391]}
        rotation={[-0.449, 0.944, 0]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane53_leaf_0.geometry}
        material={materials.leaf}
        position={[-1.029, 7.496, -0.35]}
        rotation={[-0.807, -0.04, 0.733]}
        scale={[1.226, 0.736, 0.736]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane54_leaf_0.geometry}
        material={materials.leaf}
        position={[1.905, 6.52, 1.067]}
        rotation={[0.593, 0, -0.125]}
        scale={[1.667, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane55_leaf_0.geometry}
        material={materials.leaf}
        position={[0.816, 6.334, 1.513]}
        rotation={[-2.437, -0.828, 2.948]}
        scale={[1.199, 0.72, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane56_leaf_0.geometry}
        material={materials.leaf}
        position={[-0.928, 6.231, 0.136]}
        rotation={[-2.368, -0.961, -2.922]}
        scale={[1.667, 1, 1]}
      />
    </group>
  );
};

export default Bonsai;
