/*
Meshes auto-generated by: https://github.com/pmndrs/gltfjsx
Author: rikugo.studio (https://sketchfab.com/rikugo.studio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-calendar-023e3d2170f54b219d4d44bea2075f36
Title: Simple Calendar
*/

import { useGLTF } from "@react-three/drei";
import calendarScene from "../assets/calendar.glb";

const Calendar = (props) => {
  const { nodes, materials } = useGLTF(calendarScene);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial001}
        position={[0, 0, 0.052]}
        rotation={[-0.308, 0, 0]}
        scale={1.115}
      />
    </group>
  );
};

export default Calendar;
