/*
Meshes auto-generated by: https://github.com/pmndrs/gltfjsx
Author: e Rac (https://sketchfab.com/e_rac)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-chess-set-0e8aa570aa5448eca820d8ae760d663b
Title: Low Poly Chess Set
*/

import { useGLTF } from "@react-three/drei";
import chessScene from "../assets/chess.glb";

const Chess = (props) => {
  const { nodes, materials } = useGLTF(chessScene);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.622}
      />
    </group>
  );
};

useGLTF.preload(chessScene);
export default Chess;
