/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Laetitia Irata (https://sketchfab.com/LaetitiaIrata)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/quest-compass-2-3ff33f5baae24b9eab100442fce797e7
Title: Quest Compass 2
*/

import compassScene from "../assets/compass.glb";
import { useGLTF } from "@react-three/drei";

const Compass = (props) => {
  const { nodes, materials } = useGLTF(compassScene);
  return (
    <group {...props} dispose={null}>
      <lineSegments
        geometry={nodes.Material3.geometry}
        material={materials.PaletteMaterial001}
        position={[-44.115, 0, 44.202]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2.geometry}
        material={materials.PaletteMaterial002}
        position={[-44.115, 0, 44.202]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_1.geometry}
        material={materials.Compass_Rose}
        position={[-35.217, 3.937, 35.287]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2_2.geometry}
        material={materials.PaletteMaterial001}
        position={[-35.217, 14.173, 35.287]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload(compassScene);
export default Compass;
