/*
Meshes auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Jamie McFarlane (https://sketchfab.com/jamiemcfarlane)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fancy-gramophone-d523fdd39afd4a7db6bbb5ba0d2a8064
Title: Fancy Gramophone
*/

import { useGLTF } from "@react-three/drei";
import gramphoneScene from "../assets/gramophone.glb";

const Gramophone = (props) => {
  const { nodes, materials } = useGLTF(gramphoneScene);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial.geometry}
        material={materials.initialShadingGroup}
      />
    </group>
  );
};
export default Gramophone;
