/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import homegirlScene from "../assets/homegirl.glb"
import { useFrame } from '@react-three/fiber'

const HomeGirl = (props) => {
  const { nodes, materials, animations } = useGLTF(homegirlScene)

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.girl_watercolor_girl_0.geometry}
          material={materials.watercolor_girl}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  )
}

export default HomeGirl;
