/*
Meshes auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Anna Espenstein (https://sketchfab.com/Anna.Espenstein)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/handpainted-watercolor-anime-girl-b6e4176f7cb5494f997ad1fa08bbef18
Title: Handpainted watercolor anime girl
*/
import { useGLTF } from '@react-three/drei'
import homegirlScene from "../assets/homegirl.glb"

const HomeGirl = (props) => {
  const { nodes, materials } = useGLTF(homegirlScene)

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.girl_watercolor_girl_0.geometry}
        material={materials.watercolor_girl}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.01}
      />
    </group>
  )
}

export default HomeGirl;
