/*
Meshes auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Hadrien59 (https://sketchfab.com/Hadrien59)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/swiss-army-knife-bf9e6f7de2a24d169f3e6236ab3096b4
Title: Swiss Army Knife
*/

import { useGLTF } from "@react-three/drei";
import knifeScene from "../assets/knife.glb";
const Knife = (props) => {
  const { nodes, materials } = useGLTF(knifeScene);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

export default Knife;
