/*
Meshes auto-generated by: https://github.com/pmndrs/gltfjsx
Author: nicolekeane (https://sketchfab.com/nicolekeane)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/matilda-7ddedfb652bd4ea091bc3de27f98fc02
Title: Matilda
*/

import { useGLTF } from "@react-three/drei";
import matildaScene from "../assets/matilda.glb";
import QuestionTest from "@/components/questions/QuestionContainer";

const Matilda = ({ nextQuestion, previousQuestion, backgroundColor, ...props }) => {
  const { nodes, materials } = useGLTF(matildaScene);

  return (
    <group {...props} dispose={null}>
    <mesh
      castShadow
      receiveShadow
      geometry={nodes.polySurface1_surfaceShader1_0.geometry}
      material={materials.surfaceShader1}
    />
  </group>
  );
};

export default Matilda;
