/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Klasy (https://sketchfab.com/Klasy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/vintage-microphone-a5986b39102f47c5b32b212365dd7276
Title: Vintage Microphone
*/

import { useGLTF } from "@react-three/drei";
import microphoneScene from "../assets/microphone.glb";

const Microphone = (props) => {
  const { nodes, materials } = useGLTF(microphoneScene);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle__0.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.849, 0.849, 1]}
      />
    </group>
  );
};

useGLTF.preload(microphoneScene);
export default Microphone;
