/*
Meshes auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Alissa T (https://sketchfab.com/foxywild)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rainbow-6d84300eb53c49ce81824d809bcb165b
Title: Rainbow
*/

import { useGLTF } from "@react-three/drei";
import rainbowScene from "../assets/rainbow.glb";

const Rainbow = (props) => {
  const { nodes, materials } = useGLTF(rainbowScene);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.PaletteMaterial001}
        position={[0, -77.5, 48.5]}
        rotation={[-Math.PI, 0, 0]}
        scale={0.091}
      />
    </group>
  );
};

export default Rainbow;
