/*
Meshes auto-generated by: https://github.com/pmndrs/gltfjsx
Author: anastasiaremezova (https://sketchfab.com/anastasiaremezova)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-Trips/milk-delivery-b41e30c422d943409291050b77364568
Title: Milk Delivery
*/
import QuestionTest from "@/components/questions/QuestionContainer";
import tripScene from "../assets/trip.glb";
import { useGLTF } from "@react-three/drei";

const Trip = ({ addAnswer, nextQuestion, previousQuestion, ...props }) => {
  const { nodes, materials } = useGLTF(tripScene);

  return (
    <QuestionTest
      cameraPosition={[1.3, 0.4, -0.06]}
      currentQuestion={0}
      nextQuestion={nextQuestion}
      previousQuestion={previousQuestion}
    >
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface620_stone_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface652_trees_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface652_ground_0.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1294_ground_0.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1294_trees_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube9_grassss_0.geometry}
          material={materials.PaletteMaterial004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1312_stone_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere9_ground_0.geometry}
          material={materials.PaletteMaterial002}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere14_stone_0.geometry}
          material={materials.PaletteMaterial001}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pSphere20_road_0.geometry}
          material={materials.PaletteMaterial007}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube72_Clouds_0.geometry}
          material={materials.PaletteMaterial009}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface946_zabor_0.geometry}
          material={materials.PaletteMaterial001}
          position={[-0.06211234, -0.00077946, -0.06057029]}
          rotation={[0, 0.04957008, 0]}
          scale={0.00884477}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface586_ground_0.geometry}
          material={materials.PaletteMaterial002}
          position={[-0.27872188, 0.02314962, -0.11003465]}
          rotation={[-3.13168604, -1.1824898, -3.05164059]}
          scale={0.00399186}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1200_tykva_0.geometry}
          material={materials.PaletteMaterial003}
          position={[0.0756451, -0.00330776, 0.11327371]}
          rotation={[0, 0.57024606, 0]}
          scale={0.00598215}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1200_grassss_0.geometry}
          material={materials.PaletteMaterial004}
          position={[0.0756451, -0.00330776, 0.11327371]}
          rotation={[0, 0.57024606, 0]}
          scale={0.00598215}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1352_grass_0.geometry}
          material={materials.PaletteMaterial005}
          position={[-0.06168618, -0.00457123, -0.04038849]}
          scale={[0.15483071, 0.01033777, 0.15483071]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface1352_ground2_0.geometry}
          material={materials.PaletteMaterial006}
          position={[-0.06168618, -0.00457123, -0.04038849]}
          scale={[0.15483071, 0.01033777, 0.15483071]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pPlane4_road_0.geometry}
          material={materials.PaletteMaterial007}
          position={[0.015894, 0.00114969, -0.04499324]}
          scale={[0.03675383, 0.01, 0.28785383]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface385_LP2_vespa_0.geometry}
          material={materials.vespa}
          position={[0, 0, -0.01599711]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.polySurface441_LP4_Cat_0.geometry}
          material={materials.material_12}
          position={[0, 0, -0.01599711]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCube62_dust_0.geometry}
          material={materials.PaletteMaterial008}
          position={[0, 0, -0.01599711]}
          scale={0.01}
        />
      </group>
    </QuestionTest>
  );
};

export default Trip;
