/*
Meshes auto-generated by: https://github.com/pmndrs/gltfjsx
Author: anastasiaremezova (https://sketchfab.com/anastasiaremezova)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-Trips/milk-delivery-b41e30c422d943409291050b77364568
Title: Milk Delivery
*/
import tripScene from "../assets/trip.glb";
import { useGLTF } from "@react-three/drei";

const Trip = ({
  addAnswer,
  nextQuestion,
  previousQuestion,
  backgroundColor,
  ...props
}) => {
  const { nodes, materials } = useGLTF(tripScene);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface946_zabor_0.geometry}
        material={materials.PaletteMaterial001}
        position={[-0.062, -0.001, -0.061]}
        rotation={[0, 0.05, 0]}
        scale={0.009}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface586_ground_0.geometry}
        material={materials.PaletteMaterial002}
        position={[-0.279, 0.023, -0.11]}
        rotation={[-3.132, -1.182, -3.052]}
        scale={0.004}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface1200_tykva_0.geometry}
        material={materials.PaletteMaterial003}
        position={[0.076, -0.003, 0.113]}
        rotation={[0, 0.57, 0]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface1200_grassss_0.geometry}
        material={materials.PaletteMaterial004}
        position={[0.076, -0.003, 0.113]}
        rotation={[0, 0.57, 0]}
        scale={0.006}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface1352_grass_0.geometry}
        material={materials.PaletteMaterial005}
        position={[-0.062, -0.005, -0.04]}
        scale={[0.155, 0.01, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface1352_ground2_0.geometry}
        material={materials.PaletteMaterial006}
        position={[-0.062, -0.005, -0.04]}
        scale={[0.155, 0.01, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pPlane4_road_0.geometry}
        material={materials.PaletteMaterial007}
        position={[0.016, 0.001, -0.045]}
        scale={[0.037, 0.01, 0.288]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface385_LP2_vespa_0.geometry}
        material={materials.vespa}
        position={[0, 0, -0.016]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface441_LP4_Cat_0.geometry}
        material={materials.material_12}
        position={[0, 0, -0.016]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube62_dust_0.geometry}
        material={materials.PaletteMaterial008}
        position={[0, 0, -0.016]}
        scale={0.01}
      />
    </group>
  );
};

useGLTF.preload(tripScene);
export default Trip;
