/*
Meshes auto-generated by: https://github.com/pmndrs/gltfjsx
Author: anastasiaremezova (https://sketchfab.com/anastasiaremezova)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-Trips/milk-delivery-b41e30c422d943409291050b77364568
Title: Milk Delivery
*/
import QuestionTest from "@/components/questions/QuestionContainer";
import tripScene from "../assets/milk_delivery.glb";
import { useGLTF } from "@react-three/drei";

const Trip = ({ addAnswer, nextQuestion, previousQuestion, ...props }) => {
  const { nodes, materials } = useGLTF(tripScene);

  return (
    <QuestionTest
      cameraPosition={[1.3, 0.4, -0.06]}
      currentQuestion={0}
      nextQuestion={nextQuestion}
      previousQuestion={previousQuestion}
    >
      <group {...props} dispose={null}>
        <group scale={0.01}>
          <group
            position={[-27.872, 2.315, -11.003]}
            rotation={[-3.132, -1.182, -3.052]}
            scale={0.399}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface586_cow_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface586_ground_0.geometry}
              material={materials.ground}
            />
          </group>
          <group
            position={[7.565, -0.331, 11.327]}
            rotation={[0, 0.57, 0]}
            scale={0.598}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1200_tykva_0.geometry}
              material={materials.tykva}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1200_grassss_0.geometry}
              material={materials.grassss}
            />
          </group>
          <group
            position={[-43.859, 2.693, 33.318]}
            scale={[0.683, 0.796, 0.683]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface645_trees_0.geometry}
              material={materials.trees}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface645_ground_0.geometry}
              material={materials.ground}
            />
          </group>
          <group
            position={[-44.669, 3.126, 32.153]}
            scale={[0.683, 0.796, 0.683]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface652_trees_0.geometry}
              material={materials.trees}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface652_ground_0.geometry}
              material={materials.ground}
            />
          </group>
          <group position={[-53.358, 1.489, 40.17]} scale={0.856}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1294_ground_0.geometry}
              material={materials.ground}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1294_trees_0.geometry}
              material={materials.trees}
            />
          </group>
          <group
            position={[-59.559, 2.952, 33.328]}
            rotation={[0, -0.215, 0]}
            scale={[0.708, 0.824, 0.708]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1303_ground_0.geometry}
              material={materials.ground}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1303_trees_0.geometry}
              material={materials.trees}
            />
          </group>
          <group
            position={[-41.252, 2.165, 30.663]}
            rotation={[0, -0.215, 0]}
            scale={[0.539, 0.628, 0.539]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1304_trees_0.geometry}
              material={materials.trees}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1304_ground_0.geometry}
              material={materials.ground}
            />
          </group>
          <group
            position={[-82.386, 1.912, 57.452]}
            rotation={[0, -0.215, 0]}
            scale={[1.145, 1.334, 1.145]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1305_ground_0.geometry}
              material={materials.ground}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1305_trees_0.geometry}
              material={materials.trees}
            />
          </group>
          <group
            position={[-70.295, -1.125, 65.228]}
            rotation={[0, -0.215, 0]}
            scale={[1.145, 1.334, 1.145]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1306_ground_0.geometry}
              material={materials.ground}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1306_trees_0.geometry}
              material={materials.trees}
            />
          </group>
          <group
            position={[-7.777, -0.457, -4.039]}
            scale={[17.542, 1.171, 17.542]}
          >
            <group position={[0.092, 0, 0]} scale={0.883}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.polySurface1352_ground_0.geometry}
                material={materials.ground}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.polySurface1352_grass_0.geometry}
                material={materials.grass}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.polySurface1352_grassss_0.geometry}
                material={materials.grassss}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.polySurface1352_ground2_0.geometry}
                material={materials.ground2}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.polySurface1353_grassss_0.geometry}
                material={materials.grassss}
                position={[0, 0.988, 0]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1315_ground2_0.geometry}
              material={materials.ground2}
              position={[0, -0.85, -0.035]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1316_ground2_0.geometry}
              material={materials.ground2}
              position={[0.008, -0.826, 0.433]}
              rotation={[0, 0.243, 0]}
              scale={0.977}
            />
          </group>
          <group
            position={[-34.271, 9.976, 24.55]}
            rotation={[-0.229, 0, 0]}
            scale={0.619}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface610_cow_0.geometry}
              material={materials.material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface610_ground_0.geometry}
              material={materials.ground}
            />
          </group>
          <group
            position={[20.957, -0.528, 11.816]}
            rotation={[0, 1.398, 0]}
            scale={0.598}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1311_lambert15_0.geometry}
              material={materials.lambert15}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1311_grassss_0.geometry}
              material={materials.grassss}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1311_tykva_0.geometry}
              material={materials.tykva}
            />
          </group>
          <group
            position={[-59.559, 2.831, 26.622]}
            rotation={[0, -0.215, 0]}
            scale={[0.708, 0.824, 0.708]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1321_ground_0.geometry}
              material={materials.ground}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1321_trees_0.geometry}
              material={materials.trees}
            />
          </group>
          <group
            position={[-14.468, 3.764, 37.041]}
            rotation={[0, 0.607, 0]}
            scale={[0.683, 0.796, 0.683]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1323_trees_0.geometry}
              material={materials.trees}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.polySurface1323_ground_0.geometry}
              material={materials.ground}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface946_zabor_0.geometry}
            material={materials.zabor}
            position={[-6.211, -0.078, -6.057]}
            rotation={[0, 0.05, 0]}
            scale={0.884}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface620_stone_0.geometry}
            material={materials.stone}
            position={[-36.666, 35.38, -0.709]}
            rotation={[-0.921, -0.637, -1.146]}
            scale={0.672}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pPlane4_road_0.geometry}
            material={materials.road}
            position={[1.589, 0.115, -4.499]}
            scale={[3.675, 1, 28.785]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube9_grassss_0.geometry}
            material={materials.grassss}
            position={[-21.264, 0.611, 14.692]}
            rotation={[0, 1.052, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube10_grassss_0.geometry}
            material={materials.grassss}
            position={[-23.265, 0.988, -3.611]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube11_grassss_0.geometry}
            material={materials.grassss}
            position={[-23.476, 1.873, 9.72]}
            rotation={[0, 0.807, 0]}
            scale={0.789}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube12_grassss_0.geometry}
            material={materials.grassss}
            position={[-24.576, 2.187, 7.386]}
            rotation={[0, 0.543, 0]}
            scale={0.716}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube13_grassss_0.geometry}
            material={materials.grassss}
            position={[-20.891, 2.187, -3.829]}
            rotation={[0, -0.406, 0]}
            scale={0.716}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube14_grassss_0.geometry}
            material={materials.grassss}
            position={[-21.389, 2.543, -2.39]}
            rotation={[0, -0.406, 0]}
            scale={0.716}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1310_stone_0.geometry}
            material={materials.stone}
            position={[-49.594, -0.166, 2.019]}
            rotation={[0, -0.752, 0]}
            scale={0.672}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1312_stone_0.geometry}
            material={materials.stone}
            position={[-43.834, 2.38, -68.406]}
            rotation={[-Math.PI, -1.218, -Math.PI]}
            scale={0.85}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1313_stone_0.geometry}
            material={materials.stone}
            position={[-46.852, 2.376, -43.596]}
            rotation={[-Math.PI, -1.218, -Math.PI]}
            scale={0.85}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1237_ground_0.geometry}
            material={materials.ground}
            position={[-15.569, 2.816, 18.164]}
            scale={0.297}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube25_grassss_0.geometry}
            material={materials.grassss}
            position={[-1.381, -2.178, -2.262]}
            rotation={[0.036, 0.269, -0.134]}
            scale={[0.606, 0.949, 0.606]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube26_grassss_0.geometry}
            material={materials.grassss}
            position={[7.629, -1.889, -11.491]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube27_grassss_0.geometry}
            material={materials.grassss}
            position={[-8.173, -1.394, -6.793]}
            rotation={[-0.113, -1.162, -0.263]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube28_grassss_0.geometry}
            material={materials.grassss}
            position={[-11.353, -0.347, -8.873]}
            rotation={[0.153, 0.493, -0.315]}
            scale={0.804}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube29_grassss_0.geometry}
            material={materials.grassss}
            position={[-9.978, -0.596, -9.441]}
            rotation={[0.153, 0.493, -0.315]}
            scale={0.804}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube30_grassss_0.geometry}
            material={materials.grassss}
            position={[-3.321, -0.398, -0.265]}
            rotation={[0.055, -0.028, -0.085]}
            scale={[1, 1.153, 0.797]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube31_grassss_0.geometry}
            material={materials.grassss}
            position={[-12.413, 3.477, -3.661]}
            rotation={[-0.187, -0.547, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere9_ground_0.geometry}
            material={materials.ground}
            position={[1.309, 0.013, 1.786]}
            rotation={[0.073, 0, 0]}
            scale={0.692}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere10_ground_0.geometry}
            material={materials.ground}
            position={[4.192, 0.222, 0.385]}
            rotation={[-0.286, -1.119, -0.35]}
            scale={0.692}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere11_ground_0.geometry}
            material={materials.ground}
            position={[6.576, -0.458, 6.037]}
            rotation={[0.117, 1.1, -0.099]}
            scale={0.692}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere12_ground_0.geometry}
            material={materials.ground}
            position={[6.522, -0.759, 0.177]}
            rotation={[-0.11, 1.011, 0.266]}
            scale={0.692}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere13_ground_0.geometry}
            material={materials.ground}
            position={[4.586, 0.081, -5.568]}
            rotation={[0.221, -1.215, 0.101]}
            scale={0.692}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere14_stone_0.geometry}
            material={materials.stone}
            position={[-5.399, 0.097, 8.662]}
            rotation={[-0.028, 0.044, 0.014]}
            scale={0.987}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere15_stone_0.geometry}
            material={materials.stone}
            position={[-1.154, -0.057, 7.197]}
            rotation={[-0.187, 1.422, 0.198]}
            scale={[1.557, 0.948, 1.557]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere16_stone_0.geometry}
            material={materials.stone}
            position={[5.003, 0.288, -14.762]}
            rotation={[-3.107, 0.664, 3.133]}
            scale={1.557}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere17_ground_0.geometry}
            material={materials.ground}
            position={[0.87, 0.099, -1.621]}
            rotation={[-0.041, -0.536, -0.027]}
            scale={[0.692, 0.576, 0.692]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere18_ground_0.geometry}
            material={materials.ground}
            position={[2.604, 0.161, -8.018]}
            rotation={[-0.095, -1.187, -0.094]}
            scale={0.692}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere19_ground_0.geometry}
            material={materials.ground}
            position={[0.973, -0.041, -5.241]}
            rotation={[0.061, -0.651, 0.055]}
            scale={0.692}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube33_grassss_0.geometry}
            material={materials.grassss}
            position={[-1.536, -3.348, 2.099]}
            rotation={[0.017, -0.16, 0]}
            scale={[1, 1.962, 0.884]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube34_grassss_0.geometry}
            material={materials.grassss}
            position={[0.72, -2.961, -0.187]}
            rotation={[-0.114, -0.388, -0.243]}
            scale={[0.704, 0.978, 0.704]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube35_grassss_0.geometry}
            material={materials.grassss}
            position={[1.089, -2.804, -1.829]}
            rotation={[0.1, 0, -0.201]}
            scale={0.709}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube36_grassss_0.geometry}
            material={materials.grassss}
            position={[-6.985, -0.704, 7.294]}
            rotation={[0, 0, -0.201]}
            scale={0.74}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube37_grassss_0.geometry}
            material={materials.grassss}
            position={[3.22, -3.451, 15.129]}
            rotation={[-0.087, -0.321, -0.112]}
            scale={[1, 1.34, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube38_grassss_0.geometry}
            material={materials.grassss}
            position={[-4.029, -1.211, 7.625]}
            rotation={[0.038, 0, -0.201]}
            scale={0.681}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere20_road_0.geometry}
            material={materials.road}
            position={[3.729, -0.029, -13.446]}
            rotation={[-3.14, -0.134, -3.085]}
            scale={0.692}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere21_road_0.geometry}
            material={materials.road}
            position={[-3.142, -0.029, -13.026]}
            rotation={[-0.002, -0.365, 0.056]}
            scale={0.692}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere22_road_0.geometry}
            material={materials.road}
            position={[-3.607, -0.029, -9.216]}
            rotation={[-0.002, -0.365, 0.056]}
            scale={0.692}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere26_road_0.geometry}
            material={materials.road}
            position={[-3.332, 0, 1.899]}
            rotation={[0, 0.204, 0]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface385_LP2_vespa_0.geometry}
            material={materials.vespa}
            position={[0, 0, -1.6]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface441_LP4_Cat_0.geometry}
            material={materials.material_12}
            position={[0, 0, -1.6]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube62_dust_0.geometry}
            material={materials.dust}
            position={[0, 0, -1.6]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1317_zabor_0.geometry}
            material={materials.zabor}
            position={[-2.648, -0.078, -27.604]}
            rotation={[0, -0.233, 0]}
            scale={0.884}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1318_stone_0.geometry}
            material={materials.stone}
            position={[-65.752, 3.096, 38.836]}
            rotation={[0, -0.11, 0]}
            scale={1.063}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube63_grassss_0.geometry}
            material={materials.grassss}
            position={[6.143, -3.657, -4.412]}
            rotation={[0.011, 0.251, -0.153]}
            scale={[0.704, 0.984, 0.704]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube64_grassss_0.geometry}
            material={materials.grassss}
            position={[-24.899, 2.543, 3.623]}
            rotation={[0, 0.249, 0]}
            scale={0.716}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube65_grassss_0.geometry}
            material={materials.grassss}
            position={[-24.401, 2.187, 2.183]}
            rotation={[0, 0.249, 0]}
            scale={0.716}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube66_grassss_0.geometry}
            material={materials.grassss}
            position={[-20.903, 2.187, 13.773]}
            rotation={[0, 1.198, 0]}
            scale={0.716}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube67_grassss_0.geometry}
            material={materials.grassss}
            position={[-25.485, 3.014, -2.381]}
            rotation={[0, -0.14, 0]}
            scale={0.716}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube68_grassss_0.geometry}
            material={materials.grassss}
            position={[-24.987, 2.658, -3.82]}
            rotation={[0, -0.14, 0]}
            scale={0.716}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube69_grassss_0.geometry}
            material={materials.grassss}
            position={[-25.792, 2.658, 8.119]}
            rotation={[0, 0.81, 0]}
            scale={0.716}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube70_grassss_0.geometry}
            material={materials.grassss}
            position={[9.443, -3.451, -1.474]}
            rotation={[-0.149, 0.983, 0.04]}
            scale={[1, 1.34, 1]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube71_grassss_0.geometry}
            material={materials.grassss}
            position={[-2.414, -1.956, 6.422]}
            rotation={[-0.012, -0.063, -0.13]}
            scale={[0.542, 1.062, 0.542]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere27_stone_0.geometry}
            material={materials.stone}
            position={[-4.229, 1.45, -11.457]}
            rotation={[-3.048, -0.185, -3.021]}
            scale={[1.203, 0.732, 1.203]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube72_Clouds_0.geometry}
            material={materials.Clouds}
            position={[-13.77, 8.191, 7.403]}
            scale={[1.354, 1.354, 1.762]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube73_Clouds_0.geometry}
            material={materials.Clouds}
            position={[-18.578, 7.02, 0.032]}
            rotation={[-Math.PI, -0.637, -Math.PI]}
            scale={[1.05, 1.05, 1.367]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube74_Clouds_0.geometry}
            material={materials.Clouds}
            position={[-22.043, 6.843, 3.814]}
            rotation={[0, 0.073, 0]}
            scale={[1.354, 1.354, 1.762]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube75_Clouds_0.geometry}
            material={materials.Clouds}
            position={[-15.323, 8.868, -2.801]}
            rotation={[0, 0.073, 0]}
            scale={[0.685, 0.685, 0.891]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube76_Clouds_0.geometry}
            material={materials.Clouds}
            position={[-16.573, 9.917, -10.951]}
            rotation={[-0.088, -0.87, -0.328]}
            scale={[0.732, 0.732, 0.953]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1325_stone_0.geometry}
            material={materials.stone}
            position={[0.198, 2.833, -5.208]}
            rotation={[0, 0, 0.167]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube77_Clouds_0.geometry}
            material={materials.Clouds}
            position={[-22.639, 8.408, 6.459]}
            rotation={[0, -0.93, 0]}
            scale={[0.779, 0.779, 1.013]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube78_Clouds_0.geometry}
            material={materials.Clouds}
            position={[-7.655, 6.564, -20.209]}
            rotation={[-3.068, 0.696, 2.834]}
            scale={[0.732, 0.732, 0.953]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.polySurface1351_stone_0.geometry}
            material={materials.stone}
            position={[-21.141, 18.808, 39.065]}
            rotation={[-0.972, -0.549, 1.798]}
            scale={0.85}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube115_Clouds_0.geometry}
            material={materials.Clouds}
            position={[-13.446, 9.605, -0.238]}
            rotation={[-Math.PI, -0.761, -Math.PI]}
            scale={[1.05, 1.05, 1.367]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pCube116_Clouds_0.geometry}
            material={materials.Clouds}
            position={[-14.744, 6.843, -12.341]}
            rotation={[0, -1.1, 0]}
            scale={[1.354, 1.354, 1.762]}
          />
        </group>
      </group>
    </QuestionTest>
  );
};

export default Trip;
